[package]
name = "rssl-parser"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
rssl-text = { path = "../text" }
rssl-ast = { path = "../ast" }

[dev-dependencies]
rssl-preprocess = { path = "../preprocess" }
